Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/bin/daphne", line 8, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/daphne/cli.py", line 171, in entrypoint
    cls().run(sys.argv[1:])
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/daphne/cli.py", line 239, in run
    application = self.load_asgi_app(args.application)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/daphne/cli.py", line 208, in load_asgi_app
    return import_by_path(asgi_app_path)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/daphne/utils.py", line 17, in import_by_path
    target = importlib.import_module(module_path)
  File "/nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python3-3.10.16/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/workspace/./django_project/asgi.py", line 13, in <module>
    from jokes.consumers import YourConsumer
  File "/home/runner/workspace/./jokes/consumers.py", line 5, in <module>
    from .models import Joke
  File "/home/runner/workspace/./jokes/models.py", line 5, in <module>
    class ContactMessage(models.Model):
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.